#!/bin/bash

MEMBERSID=`nmcli c show | awk '/^The Mill-MEMBERS/ {print $3}'`
GUESTSID=`nmcli c show | awk '/^The Mill-GUESTS/ {print $3}'`

show_usage() {
  cat <<INS
updatemillpassword [members] [guests]

members - new password for the members network
guests - new password for the guests network
INS

  exit 1

}

update_connection_password() {
  nmcli c modify $1 802-11-wireless-security.psk $2
}

update_members() {
  update_connection_password $MEMBERSID $1
}  

update_guests() {
  update_connection_password $GUESTSID $1
}  

toggle_connection() {
  nmcli r wifi off
  nmcli r wifi on
}

if [[ $# -eq 0 ]]; then
  show_usage
fi

if [[ $# -le 2 ]]; then 
  update_members $1
fi

if [[ $# -eq 2 ]]; then
  update_guests $2
fi

toggle_connection
