#!/bin/bash

print_usage() {
  echo "increment [date]

  increment will add a line to the end of fifteendays.tsv
	it assumes that the date is today, but it is possible to pass a date in YYYY-MM-DD format on the commandline
  "
	exit 1
}

get_passed() {
	PASSED=`sqlite3 chessproblems.sqlite <<EOF
		select count(date) from chessproblems where date="$TODAY" and is_passed="true";
EOF
	`
}

get_total_attempted() {
	TOTAL_ATTEMPTED=`sqlite3 chessproblems.sqlite <<EOF
		select count(date) from chessproblems where date="$TODAY";
EOF
	`
}

get_final_score() {
	FINAL_SCORE=`sqlite3 chessproblems.sqlite <<EOF
		select my_rating from chessproblems where date="$TODAY" order by rowid desc limit 1;
EOF
	`
}

get_start_score() {
	START_SCORE=`sqlite3 chessproblems.sqlite <<EOF
		select my_rating-rating_change from chessproblems where date="$TODAY" order by rowid desc limit 1;
EOF
	`
}

DAYS=(`wc -l fifteendays.tsv`)
DAYNUM="$((${DAYS[0]} + 1))"
TODAY=`date +%F`

if [ $# -eq 1 ]; then
	if [[ $1 =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
		TODAY=$1
	else
		print_usage
	fi
fi

get_passed
get_total_attempted
get_start_score
get_final_score
echo -e "$DAYNUM\t$TODAY\t$START_SCORE\t$FINAL_SCORE\t$PASSED\t$TOTAL_ATTEMPTED" >> fifteendays.tsv
